import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
        marginRight: 0,
        marginLeft: 0,
        marginBottom: 15,
    },
    text: {
        color: '#ddd',
        textAlign: 'center',
        fontSize: 16,
    },
    input: {
        height: 40,
        fontSize: 16,
        color: '#ddd',
        borderBottomColor: '#fff',
        borderBottomWidth: 1,
    },
    modernInput: {
        height: 48,
        fontSize: 17,
        color: '#f5f5f5',
        backgroundColor: '#141414',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#2a2a2a',
        paddingHorizontal: 16,
    },
    card: {
        backgroundColor: '#0d0d0d',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#1f1f1f',
        padding: 18,
        marginBottom: 16,
    },
    fieldLabel: {
        color: '#888',
        fontSize: 13,
        fontWeight: '600',
        letterSpacing: 0.4,
        textTransform: 'uppercase',
        marginBottom: 8,
    },
    valueLarge: {
        color: '#f5f5f5',
        fontSize: 28,
        fontWeight: '600',
        marginBottom: 16,
    },
    buttonRow: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 4,
    },
    buttonPrimary: {
        minHeight: 48,
        borderRadius: 12,
        backgroundColor: '#22c55e',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'stretch',
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    buttonPrimaryInRow: {
        flex: 1,
    },
    buttonSecondary: {
        height: 48,
        borderRadius: 12,
        backgroundColor: '#1a1a1a',
        borderWidth: 1,
        borderColor: '#333',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    buttonGhost: {
        flex: 1,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonDestructive: {
        height: 48,
        borderRadius: 12,
        backgroundColor: 'rgba(220, 38, 38, 0.12)',
        borderWidth: 1,
        borderColor: 'rgba(220, 38, 38, 0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
    },
    buttonTextPrimary: {
        color: '#000',
        fontSize: 16,
        fontWeight: '700',
    },
    buttonTextSecondary: {
        color: '#ddd',
        fontSize: 16,
        fontWeight: '600',
    },
    buttonTextGhost: {
        color: '#888',
        fontSize: 16,
        fontWeight: '600',
    },
    buttonTextDestructive: {
        color: '#f87171',
        fontSize: 16,
        fontWeight: '600',
    },
    screenPadding: {
        paddingHorizontal: 16,
        paddingBottom: 32,
    },
    listRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 14,
        marginBottom: 8,
        backgroundColor: '#0d0d0d',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#1f1f1f',
    },
    listRowPressed: {
        backgroundColor: '#161616',
        borderColor: '#2a2a2a',
    },
    listRowText: {
        flex: 1,
        marginLeft: 12,
    },
    listRowName: {
        color: '#f5f5f5',
        fontSize: 16,
        fontWeight: '600',
    },
    listRowSymbol: {
        color: '#888',
        fontSize: 14,
        marginTop: 2,
    },
    emptyText: {
        color: '#666',
        fontSize: 15,
        textAlign: 'center',
        marginTop: 24,
        paddingHorizontal: 24,
    },
    sectionTitle: {
        color: '#f5f5f5',
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 8,
    },
    sectionDescription: {
        color: '#888',
        fontSize: 14,
        lineHeight: 20,
    },
    chipGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 16,
    },
    chip: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        backgroundColor: '#1a1a1a',
        borderWidth: 1,
        borderColor: '#333',
        minWidth: 58,
        alignItems: 'center',
    },
    chipActive: {
        backgroundColor: 'rgba(34, 197, 94, 0.15)',
        borderColor: '#22c55e',
    },
    chipText: {
        color: '#ddd',
        fontSize: 15,
        fontWeight: '600',
    },
    chipTextActive: {
        color: '#22c55e',
    },
    bodyText: {
        color: '#aaa',
        fontSize: 15,
        lineHeight: 22,
        marginTop: 8,
    },
    linkText: {
        color: '#22c55e',
    },
    homeToolbar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    homeScreenPadding: {
        paddingHorizontal: 8,
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#0d0d0d',
        borderWidth: 1,
        borderColor: '#1f1f1f',
        alignItems: 'center',
        justifyContent: 'center',
    },
    portfolioBalance: {
        color: '#f5f5f5',
        fontSize: 34,
        fontWeight: '700',
        letterSpacing: -0.5,
    },
    portfolioInterest: {
        color: '#22c55e',
        fontSize: 17,
        fontWeight: '600',
        marginTop: 6,
    },
    dreamBanner: {
        borderRadius: 10,
        borderWidth: 1,
        paddingVertical: 10,
        paddingHorizontal: 14,
        marginBottom: 12,
        backgroundColor: 'rgba(34, 197, 94, 0.1)',
        borderColor: 'rgba(34, 197, 94, 0.35)',
    },
    dreamBannerNegative: {
        backgroundColor: 'rgba(220, 38, 38, 0.1)',
        borderColor: 'rgba(220, 38, 38, 0.35)',
    },
    dreamBannerText: {
        color: '#ddd',
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    holdingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0d0d0d',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#1f1f1f',
        paddingVertical: 12,
        paddingHorizontal: 14,
    },
    holdingRowEmbedded: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    holdingRowActive: {
        borderColor: '#22c55e',
        backgroundColor: '#111811',
    },
    holdingMain: {
        flex: 1,
        marginLeft: 12,
        minWidth: 0,
    },
    holdingValues: {
        alignItems: 'flex-end',
        justifyContent: 'center',
        marginLeft: 8,
        maxWidth: '48%',
    },
    holdingName: {
        color: '#f5f5f5',
        fontSize: 16,
        fontWeight: '600',
    },
    holdingMeta: {
        color: '#888',
        fontSize: 13,
        marginTop: 3,
    },
    holdingBalance: {
        color: '#22c55e',
        fontSize: 15,
        fontWeight: '700',
        textAlign: 'right',
    },
    holdingInterest: {
        color: '#666',
        fontSize: 12,
        marginTop: 3,
        textAlign: 'right',
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
});
